resources:
- name: cloud-platform-environments-repo
  type: git
  source:
    uri: https://github.com/poornima-krishnasamy/cloud-platform-environments.git
    branch: main
    git_crypt_key: ((cloud-platform-environments-git-crypt.key))
  source:
    repository: poornima-krishnasamy/cloud-platform-environments
    access_token: ((cloud-platform-environments-pr-git-access-token))
    git_crypt_key: ((cloud-platform-environments-git-crypt.key))
    paths:
    - namespaces/cp-2501-1602.cloud-platform.service.justice.gov.uk
- name: pipeline-tools-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-pipeline-tools
    tag: "1.25"
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))
- name: every-120m
  type: time
  source:
    interval: 120m

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))


groups:
- name: environments-terraform
  jobs:
    - plan-live-1

jobs:
  - name: plan-live-1
    serial: true
    plan:
      - in_parallel:
        - get: every-120m
          trigger: true
        - get: cloud-platform-environments-repo
          trigger: false
        - get: pipeline-tools-image
      - task: apply-environments
        image: pipeline-tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-environments-repo
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            KUBECONFIG: /tmp/kubeconfig
            KUBE_CONFIG_PATH: /tmp/kubeconfig            
            TF_PLUGIN_CACHE_DIR: /tmp/terraform-plugin-cache
            PINGDOM_USER: ((cloud-platform-environments-pingdom.pingdom_user))
            PINGDOM_PASSWORD: ((cloud-platform-environments-pingdom.pingdom_password))
            PINGDOM_API_KEY: ((cloud-platform-environments-pingdom.pingdom_api_key))
            # the variables prefixed with PIPELINE_ are used by the plan script
            PIPELINE_CLUSTER: cp-2501-1602.cloud-platform.service .justice.gov.uk
            PIPELINE_STATE_BUCKET: cloud-platform-terraform-state
            PIPELINE_STATE_KEY_PREFIX: "cloud-platform-environments/"
            PIPELINE_STATE_REGION: "eu-west-1"
            PIPELINE_TERRAFORM_STATE_LOCK_TABLE: "cloud-platform-environments-cp-2501-1602-terraform-lock"
            TF_VAR_cluster_name: "cp-2501-1602"
            TF_VAR_cluster_state_bucket: cloud-platform-terraform-state
            TF_VAR_concourse_url: "https://concourse.apps.cp-1501-1106.cloud-platform.service.justice.gov.uk"
            TF_VAR_concourse_basic_auth_username: ((concourse-basic-auth.username))
            TF_VAR_concourse_basic_auth_password: ((concourse-basic-auth.password))
            TF_VAR_cluster_state_key: "cloud-platform/cp-2501-1602/terraform.tfstate"
          run:
            path: /bin/sh
            dir: cloud-platform-environments-repo
            args:
              - -c
              - |
                mkdir -p "${TF_PLUGIN_CACHE_DIR}"
                (
                  aws s3 cp s3://cp-1501-1106-concourse-kubeconfig/kubeconfig /tmp/kubeconfig
                )
                bundle install --without development test
                ./bin/plan

